[package]
name = "tool-dev"
version = "0.0.0"
edition.workspace = true

[dependencies]
clap = { version = "4.4.18", features = ["derive", "cargo"] }

[dev-dependencies]
cargo-husky = { version = "1", default-features = false, features = [
    "user-hooks",
] }
